### ISSUE TITLE
Icon Update

### ISSUE THREAD

**Issue by Aerron03** [ZCube/ACTWebSocketOverlay#3]
Any chance the class icons will be updated to include Gunbreaker and Dancer now that the Shadowbringers expansion has released?

**Comment by zcube** [comment]
First of all, I am not actively managing this project. I do not play FF14. The update requires two icons and a job string. If you add PR to the image of textures, I will try to build related binaries and add jobs.

**Comment by zcube** [comment]
done

**Comment by Aerron03** [comment]
Thank you!
