### ISSUE TITLE
Wrong reshade version?

### ISSUE THREAD

**Issue by kotarou3** [ZCube/ACTWebSocketOverlay#4]
The reshade version included in your latest release (v0.1.1) seems to be wrong? 0.0.0.17 doesn't sound right. My reshade shaders end up complaining that the version is too low to work (need v3+)
![image](https://user-images.githubusercontent.com/1522164/61575211-7278fe00-ab0c-11e9-94ef-1a6aff1ab8d0.png)

Meanwhile, the reshade version of your older v0.1.0 release seems to have a proper version of 3.0.7.293:
![image](https://user-images.githubusercontent.com/1522164/61575246-bb30b700-ab0c-11e9-9610-7d041cc873d5.png)

**Comment by zcube** [comment]
Version representation is not important because it is a customized version. but I modified it to 3.0.7 and released it.
